modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_display_name}"
authors="${mod_author}"
description = '''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${required_minecraft_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "gtceu"
mandatory = true
versionRange = "[${gtceu_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "gtmthings"
mandatory = true
versionRange = "[${gtmthings_version},)"
ordering = "NONE"
side = "BOTH"